version: '3.3'
services:
  web:
    build: .
    container_name: flask-simple_notebook
    command: gunicorn -b 0.0.0.0:5000 --forwarded-allow-ips="192.168.1.123" api:app
    environment: 
      SECRET_KEY: secret123 
    volumes:
      - ./build:/usr/src/app/build
      - /etc/localtime:/etc/localtime
      - ./api.py:/usr/src/app/api.py
    ports:
            - "5000"
    restart: always

    
  nginx-flask:
        image: nginx:latest
        container_name: nginx-flask-simple_notebook
        ports:
                - "5001:443"
        volumes:
            - ./nginx/flask.conf:/etc/nginx/conf.d/flask.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/cert:/etc/nginx/cert
        links:
            - web
        restart: always
